# --- Build stage ---
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -DskipTests package

# --- Run stage ---
FROM eclipse-temurin:17-jre
WORKDIR /app
# copie le jar construit (nommé backend-0.0.1-SNAPSHOT.jar)
COPY --from=build /app/target/*.jar app.jar

# Render injecte $PORT -> Spring lira server.port=${PORT:8080}
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["java","-Dserver.port=${PORT}","-jar","/app/app.jar"]
